web:
  addr: 0.0.0.0:8080
  title: "Go File Server"
  theme: green
  debug: true
  xheaders: true
  cors: true
  upload: true
  delete: true
  noaccess: false
  admin_username: admin
  admin_password: admin
  admin_emial: admin@test.com
  root: /home/goer/httpserver
  google_tracer_id: UA-783218139-1
  no_index: false
  simpleauth: true
  prefix:

auth:
  type: http
  http: admin:admin

db:
  enable: false
  host: 127.0.0.1  # MySQL 机器 IP 和端口，默认 127.0.0.1:3306
  username: httpserver # MySQL 用户名(建议授权最小权限集)
  password: httpserver123 # MySQL 用户密码
  database: httpserver # miniblog 系统所用的数据库名
  max-idle-connections: 100 # MySQL 最大空闲连接数，默认 100
  max-open-connections: 100 # MySQL 最大打开的连接数，默认 100
  max-connection-life-time: 10s # 空闲连接最大存活时间，默认 10s
  log-level: 4 # GORM log level, 1: silent, 2:error, 3:warn, 4:info

log:
  disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件和行号
  disable-stacktrace: false # 是否禁止在 panic 及以上级别打印堆栈信息
  level: debug # 指定日志级别，可选值：debug, info, warn, error, dpanic, panic, fatal
  format: console # 指定日志显示格式，可选值：console, json
  output-paths: [/tmp/gofileserver.log, stdout] # 指定日志输出位置，多个输出，用 `逗号 + 空格` 分开。stdout：标准输
